kind: pipeline
name: default

steps:
- name: lint-unit-test
  image: gnes/ci-base
  environment:
    GNES_ENV_SET: orange-ci
    BOT_ID:
      from_secret: gnes-wechat-botid
  commands:
  - mkdir -p .cache && ln -snf $(pwd)/.cache $HOME/.cache
  - export PIP_DOWNLOAD_CACHE=${pwd}.cache/pip_download_cache && export XDG_CACHE_HOME=${pwd}.cache/pip
  - printf "XDG_CACHE_HOME=$XDG_CACHE_HOME\nPIP_DOWNLOAD_CACHE=$PIP_DOWNLOAD_CACHE\n"
  - cat /proc/cpuinfo | grep flags
  - pip install -e .[all]
  - "python -c 'import tensorflow as tf; print(tf.__version__); a=tf.constant(1, tf.int32); print(tf.Session().run(a))'"
  - pylint gnes/**/*.py --exit-zero
  - python -m unittest tests/*.py
  - >
    curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key='$BOT_ID \
       -H 'Content-Type: application/json' \
       -d '
       {
            "msgtype": "text",
            "text": {
                "content": "hello world"
            }
       }'