kind: pipeline
name: default

clone:
  depth: 50

steps:

- name: check commit style
  image: node:alpine
  commands:
  - npm install --global --save-dev @commitlint/config-conventional @commitlint/cli
  - "echo \"module.exports = {extends: ['@commitlint/config-conventional']}\" > commitlint.config.js"
  - echo $DRONE_COMMIT_MESSAGE | commitlint

- name: notify the start on wechat work
  image: byrnedo/alpine-curl
  environment:
    BOT_ID:
      from_secret: gnes-wechat-botid
  commands:
  - export MSG_LINK=${DRONE_BUILD_LINK}
  - export MSG_TITLE="🍽 Start a CI pipeline (${DRONE_BUILD_NUMBER}) for $DRONE_SOURCE_BRANCH"
  - export MSG_CONTENT="submit by $DRONE_COMMIT_AUTHOR, click the link below to see the status"
  - ./shell/push-wechatwork.sh

- name: setup ci environment
  image: gnes/ci-base
  commands:
  - mkdir -p .cache && ln -snf $(pwd)/.cache $HOME/.cache
  - export PIP_DOWNLOAD_CACHE=${pwd}.cache/pip_download_cache && export XDG_CACHE_HOME=${pwd}.cache/pip
  - printf "XDG_CACHE_HOME=$XDG_CACHE_HOME\nPIP_DOWNLOAD_CACHE=$PIP_DOWNLOAD_CACHE\n"
  - cat /proc/cpuinfo | grep flags
  - "python -c 'import tensorflow as tf; print(tf.__version__); a=tf.constant(1, tf.int32); print(tf.Session().run(a))'"

- name: pip-install gnes
  image: gnes/ci-base
  environment:
    GNES_ENV_SET: orange-ci
  commands:
  - pip install -e .[all]
  - pylint gnes/**/*.py --exit-zero
  - python -m unittest tests/*.py


- name: notify the sucess on wechat work
  image: byrnedo/alpine-curl
  environment:
    BOT_ID:
      from_secret: gnes-wechat-botid
  commands:
  - export MSG_LINK=$DRONE_REPO_LINK
  - export MSG_TITLE="✅ Looks good to me. All tests passed! (${DRONE_BUILD_NUMBER}) for $DRONE_SOURCE_BRANCH"
  - export MSG_CONTENT="the commit submit by $DRONE_COMMIT_AUTHOR is ready to merge to branch $DRONE_SOURCE_BRANCH"
  - ./shell/push-wechatwork.sh


- name: notify the failure on wechat work
  image: byrnedo/alpine-curl
  environment:
    BOT_ID:
      from_secret: gnes-wechat-botid
  commands:
  - export MSG_LINK=$DRONE_BUILD_LINK
  - export MSG_TITLE="❌ CI pipeline (${DRONE_BUILD_NUMBER}) failed!"
  - export MSG_CONTENT="please inform $DRONE_COMMIT_AUTHOR to modify and fix this branch. click the link below to see the details."
  - ./shell/push-wechatwork.sh
  when:
    status:
    - failure

trigger:
  branch:
  - master
  event:
  - pull_request