ok-stage: &ok_stage
  - name: git comment
    jobs:
      - name: make comment
        script: echo "looks good to me 👍" > comment.txt
      - name: submit comment
        type: git:comment
        options:
          fromFile: comment.txt

install-deps: &install_deps
  - name: install dependencies
    jobs:
      - name: show cpu flag
        script: cat /proc/cpuinfo | grep flags
      - name: install project deps
        env:
          INDEX_URL: http://mirrors.oa.com/pypi/web/simple/
          TRUST_DOM: mirrors.oa.com
        script: "pip install -r requirements.txt -i ${INDEX_URL} --extra-index-url ${INDEX_URL} --trusted-host ${TRUST_DOM}"
      - name: check tensorflow works correctly
        script: "python -c 'import tensorflow as tf; print(tf.__version__); a=tf.constant(1, tf.int32); print(tf.Session().run(a))'"

pylint: &pylint
  - name: check code style
    script: pylint src/**/*.py --exit-zero

unit-test: &unit_test
  - name: run unit test
    script: python -m unittest tests/*.py

basic-pipeline: &bp1
  network: devnet
  docker:
    image: docker.oa.com:8080/public/ailab-faiss-bert:latest
  env:
    BERT_CI_PORT: 7125
    BERT_CI_PORT_OUT: 7126
    BERT_CI_MODEL: /chinese_L-12_H-768_A-12
  stages:
    - <<: *install_deps
    - <<: *pylint
    - <<: *unit_test
    - <<: *ok_stage

notify-pipeline: &np1
  network: devnet
  docker:
    image: docker.oa.com:8080/public/ailab-faiss-bert:latest
  stages:
    - name: make notification
      script: echo "# 🚀 NES刚刚更新了Master分支\n## 此次更新由$ORANGE_BUILD_USER提交触发\n## 项目地址：https://git.code.oa.com/ai-innersource/nes/" > notify.md
    - name: send mail
      type: mail:send
      options:
        title: 🚀 NES刚刚更新了Master分支
        to:
          - hanhxiao
          - larryjfyan
          - madwang
        type: markdown
        fromFile: notify.md
    - name: message
      type: wework:message
      options:
        robot: f5ee526b-c6dc-4ef1-97c0-ac14594e57b0
        fromFile: notify.md

master:
  merge_request:
    - <<: *bp1
  push:
    - <<: *np1