ok-stage: &ok_stage
  - name: git comment
    jobs:
      - name: make comment
        script: echo "looks good to me 👍" > comment.txt
      - name: submit comment
        type: git:comment
        options:
          fromFile: comment.txt

basic-pipeline: &bp1
  docker:
    image: docker.oa.com:8080/public/ai-py3:v0.1
  stages:
    - name: install dependencies
      script: pip install -r requirements.txt -i http://pypi.open.oa.com/simple/ --extra-index-url http://pypi.open.oa.com/simple/ --trusted-host pypi.open.oa.com
    - name: run unit test
      script: python -m unittest tests/*.py
    - name: check code style
      script: pylint src/**/*.py --exit-zero
    - <<: *ok_stage


master:
  merge_request:
    - <<: *bp1
