master:
  push:
    - docker:
        image: docker.oa.com:8080/public/ai-py3:v0.1
      stages:
        - name: install dependencies
          script: pip install -r requirements.txt -i http://pypi.open.oa.com/simple/ --extra-index-url http://pypi.open.oa.com/simple/ --trusted-host pypi.open.oa.com
        - name: do unit test
          script: python -m unittest tests/*.py