os: linux
dist: xenial
sudo: false
language: python
services:
  - docker
python:
  - "3.6"

cache:
  - pip

env:
  # Docker
  - CONTAINER_NAME=gnes IMAGE_NAME=tencent/gnes

before_install:
  - pip install --upgrade pip
  - pip install -U pylint

  - docker --version
  # - docker rmi $(docker images -q) || true
  # - docker build -t ${IMAGE_NAME} .

install:
  - docker build -t ${IMAGE_NAME}:${TRAVIS_COMMIT} .
  - docker run -d --name ${CONTAINER_NAME} ${IMAGE_NAME}:${TRAVIS_COMMIT}
  - docker ps -a
  # wait for docker to start
  - sleep 5

before_script:
  - env > .env

after_script:
  - docker rm -f ${CONTAINER_NAME}

# command to run tests
script:
  # Test install with current version of setuptools
  # - pip install -e . --progress-bar off
  - pylint gnes/**/*.py --exit-zero
  - docker exec ${CONTAINER_NAME} python -m unittest tests/*.py

branches:
  only:
    - master

notifications:
  email: false