os: linux
sudo: false
language: python
services:
  - docker
python: # Only py3.6 for now
  - "3.6"

install:
  - pip install --upgrade pip
  # install TensorFlow from https://storage.googleapis.com/tensorflow/
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0a0-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl;
    fi
  - pip install -e . --upgrade-strategy=eager

cache:
  - pip

# command to run tests
script:
  - pylint gnes/**/*.py --exit-zero

branches:
  only:
    - master

notifications:
  email: false