os: linux
sudo: false
language: python
services:
  - docker
python: # Only py3.6 for now
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -U pylint
  # install TensorFlow (CPU version) from https://storage.googleapis.com/tensorflow/
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0a0-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl;
    fi

cache:
  - pip

# command to run tests
script:
  # Test install with current version of setuptools
  - pip install -e . --progress-bar off
  - pylint gnes/**/*.py --exit-zero

branches:
  only:
    - master

notifications:
  email: false