sudo: required
os: linux
dist: xenial
language: python
services:
  - docker
python:
  - "3.6"

cache:
  bundler: true
  directories:
    - $MODEL_DIR
    - pip

env:
  global:
    - MODEL_DIR=${TRAVIS_HOME}/ext_data
    - BERT_CI_MODEL=${MODEL_DIR}/chinese_L-12_H-768_A-12
    - ELMO_CI_MODEL=${MODEL_DIR}/zhs.model
    - FLAIR_CI_MODEL=${MODEL_DIR}/multi-forward-fast
    - GPT_CI_MODEL=${MODEL_DIR}/openai_gpt
    - GPT2_CI_MODEL=${MODEL_DIR}/openai_gpt2
    - XL_CI_MODEL=${MODEL_DIR}/transformer_xl_wt103
    - WORD2VEC_MODEL=${MODEL_DIR}/sgns.wiki.bigram-char.sample

before_install:
  - mkdir -p ${MODEL_DIR}
  - ./.travis/download.sh

  - pip install --upgrade pip
  - pip install -U pylint


  # - export TRAVIS_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
  # - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"

install:
  # Test install with current version of setuptools
  - pip install -e . --progress-bar off

before_script:
  # - mkdir ${MODEL_DIR}
  # - ./.travis/download.sh
  - env > .env

# command to run tests
script:
  - pylint gnes/**/*.py --exit-zero

# after_script:
#   - docker rm -f ${CONTAINER_NAME}

branches:
  only:
    - travis

notifications:
  email: false