version: '3.4'
services:
  encoder:
    build:
      context: .
      target: encoder
    image: docker.oa.com/public/aipd-gnes-encoder:9d67d2b
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "5310:5310"
    networks:
      - gnes-net
    command: --mode TRAIN --yaml_path /test_encoder.yml --dump_path /ext_data/test_encode.bin
    volumes:
      - "/data1/cips/test_encoder.yml:/test_encoder.yml"
      - "/data1/cips/data:/ext_data"
  indexer:
    build:
      context: .
      target: indexer
    image: docker.oa.com/public/aipd-gnes-indexer:9d67d2b
    command: --mode ADD --yaml_path /test_indexer.yml --dump_path /ext_data/test_index.bin
    volumes:
      - "/data1/cips/test_indexer.yml:/test_indexer.yml"
    networks:
      - gnes-net
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
networks:
  gnes-net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

