version: '3.4'
services:
  income-proxy:
    image: ${DOCKER_IMG_URL}
    command: >
      proxy --port_in ${INCOME_PROXY_IN} --port_out ${INCOME_PROXY_OUT}
      --socket_in PULL_BIND --socket_out PUSH_BIND
    networks:
      gnes-net:
        aliases:
          - income_proxy
    ports:
      - ${HOST_PORT_IN}:${INCOME_PROXY_IN}
  encoder:
    image: ${DOCKER_IMG_URL}
    command: >
      encode --port_in ${INCOME_PROXY_OUT} --port_out ${MIDDLEMAN_PROXY_IN}
      --socket_in PULL_CONNECT --socket_out PUSH_CONNECT
      --host_in income-proxy --host_out middleman-proxy
      --mode $SERVER_MODE --yaml_path /encoder.yml --dump_path /ext_data/test_encode.bin
    volumes:
      - "${ENCODER_YAML_PATH}:/encoder.yml"
      - "${EXT_DATA_DIR}:/ext_data"
    depends_on:
      - income-proxy
      - middleman-proxy
  middleman-proxy:
    image: ${DOCKER_IMG_URL}
    command: >
      proxy --port_in ${MIDDLEMAN_PROXY_IN} --port_out ${MIDDLEMAN_PROXY_OUT}
      --socket_in PULL_BIND --socket_out PUSH_BIND
    networks:
      gnes-net:
        aliases:
          - middleman_proxy
  indexer:
    image: ${DOCKER_IMG_URL}
    command: >
      index --port_in ${MIDDLEMAN_PROXY_OUT} --port_out ${OUTGOING_PROXY_IN}
       --socket_in PULL_CONNECT --socket_out PUSH_CONNECT
       --host_in middleman-proxy --host_out outgoing_proxy
       --mode $SERVER_MODE --yaml_path /indexer.yml --dump_path /out_data/test_index.bin
    volumes:
      - "${INDEXER_YAML_PATH}:/indexer.yml"
      - "${EXT_DATA_DIR}:/ext_data"
      - "${OUTPUT_DIR}:/out_data"
    network_mode: "host"
    depends_on:
      - middleman-proxy
      - outgoing-proxy
  outgoing-proxy:
    image: ${DOCKER_IMG_URL}
    command: >
      proxy --port_in ${OUTGOING_PROXY_IN} --port_out ${OUTGOING_PROXY_OUT}
      --socket_in PULL_BIND --socket_out PUB_BIND
    networks:
      gnes-net:
        aliases:
          - outgoing_proxy
    ports:
      - ${HOST_PORT_OUT}:${OUTGOING_PROXY_OUT}

networks:
  gnes-net:
