version: '3'
services:
  encoder:
    build: .
      target: encoder
    image: docker.oa.com:8080/public/aipd-gnes-encoder:master
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "5000:5000"
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
    networks:
      - gnes
    command: --train --yaml_path /test.yml
    volumes:
      - "/data1/cips/test.yml:/test.yml"
      - "/data1/cips/data:/ext_data"
networks:
  gnes:

