version: '3.4'
services:
  income-route:
    image: ${DOCKER_IMG_URL}
    command: >
      route --route_type MapRouteService --port_in ${INCOME_ROUTE_IN} --port_out ${INCOME_ROUTE_OUT}
      --socket_in PULL_BIND --socket_out PUSH_BIND
    networks:
      gnes-net:
        aliases:
          - income_route
    ports:
      - ${HOST_PORT_IN}:${INCOME_ROUTE_IN}
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  middleman-route:
    image: ${DOCKER_IMG_URL}
    command: >
      route --route_type=RouteService --port_in ${MIDDLEMAN_ROUTE_IN} --port_out ${MIDDLEMAN_ROUTE_OUT}
      --socket_in PULL_BIND --socket_out PUB_BIND
      --unk_msg_route DEFAULT
    networks:
      gnes-net:
        aliases:
          - middleman_route
    deploy:
      placement:
        constraints: [node.role == worker]

  outgoing-route:
    image: ${DOCKER_IMG_URL}
    command: >
      route --route_type=ReduceRouteService --port_in ${OUTGOING_ROUTE_IN} --port_out ${OUTGOING_ROUTE_OUT}
      --socket_in SUB_BIND --socket_out PUB_BIND --num_part=$NUM_REPLICAS
      --unk_msg_route DEFAULT
    networks:
      gnes-net:
        aliases:
          - outgoing_route
    ports:
      - ${HOST_PORT_OUT}:${OUTGOING_ROUTE_OUT}
    deploy:
      placement:
        constraints: [node.role == worker]

  encoder:
    image: ${DOCKER_IMG_URL}
    command: >
      encode --port_in ${INCOME_ROUTE_OUT} --port_out ${MIDDLEMAN_ROUTE_IN}
      --socket_in PULL_CONNECT --socket_out PUSH_CONNECT
      --host_in income-route --host_out middleman-route
      --mode QUERY --yaml_path /encoder.yml --dump_path /dump/model.bin
    volumes:
      - "${ENCODER_YAML_PATH}:/encoder.yml"
      - "${MODEL_DIR}:/ext_data"
      - "${OUTPUT_DIR}:/dump"
    networks:
      gnes-net:
        aliases:
          - encoder_serviced
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

    depends_on:
      - income-route
      - middleman-route

  indexer:
    image: ${DOCKER_IMG_URL}
    command: >
      index --port_in ${MIDDLEMAN_ROUTE_OUT} --port_out ${OUTGOING_ROUTE_IN}
       --socket_in SUB_CONNECT --socket_out PUB_CONNECT
       --host_in middleman-route --host_out outgoing-route
       --mode QUERY --yaml_path /indexer.yml --dump_path /out_data/index.bin
    volumes:
      - "${INDEXER_YAML_PATH}:/indexer.yml"
      - index_data:/out_data
      #- type: volume
      #  source: "index_data"
      #  target: "/out_data"

      #- "${OUTPUT_DIR}/indexer_dump.{{.Task.Slot}}:/out_data"

    deploy:
      replicas: ${NUM_REPLICAS}
      restart_policy:
        condition: on-failure
        max_attempts: 3

    environment:
      - NODE_ID={{.Node.ID}}
      - SERVICE_ID={{.Service.ID}}
      - SERVICE_NAME={{.Service.Name}}
      - SERVICE_LABELS={{.Service.Labels}}
      - TASK_ID={{.Task.ID}}
      - TASK_NAME={{.Task.Name}}
      - TASK_SLOT={{.Task.Slot}}

    networks:
      gnes-net:
        aliases:
          - index_serviced
    depends_on:
      - middleman-route
      - outgoing-route

volumes:
  index_data:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "ubuntu@172.17.0.8:/data/larry/save_data/shard_{{ .Task.Slot }}_data"
      password: "!QAZ2wsx#EDC"
      allow_other: ""
    name: 'shard_{{ .Task.Slot }}_data'
    #external:
    #  name: 'index_shard_{{ .Task.Slot }}_data'

networks:
  gnes-net:
    driver: overlay
    attachable: true
