!MultiheadIndexer
component:
  binary_indexer: !BIndexer
    parameter:
      num_bytes: 8
      data_path: /out_data/idx.binary
  sent_doc_indexer: !LVDBIndexer
    parameter:
      data_path: /out_data/idx.sent_doc
  doc_content_indexer: !LVDBIndexer
    parameter:
      data_path: /out_data/idx.doc_content