version: '3.4'
services:
  preprocess:
    image: ${DOCKER_IMG_URL}
    command: >
      preprocess --port_in ${PREPROCESSOR_IN} --port_out ${PREPROCESSOR_OUT}
      --socket_in PULL_BIND --socket_out PUSH_CONNECT
      --host_out encoder_serviced
      --yaml_path /preprocessor_config --dump_path /dump/preprocessor.bin
    networks:
      gnes-net:
        aliases:
          - preprocessor_serviced
    configs:
      - preprocessor_config

  encoder:
    image: ${DOCKER_IMG_URL}
    command: >
      encode --port_in ${PREPROCESSOR_OUT} --port_out ${ENCODER_OUT}
      --socket_in PULL_CONNECT --socket_out PUB_BIND
      --host_in preprocessor_serviced --host_out middleman-route
      --yaml_path /encoder_config --dump_path /dump/model.bin
    volumes:
      - "${MODEL_DIR}:/ext_data"
      - "${OUTPUT_DIR}:/dump"
    networks:
      gnes-net:
        aliases:
          - encoder_serviced
    deploy:
      replicas: ${NUM_ENCODER}
      restart_policy:
        condition: on-failure
        max_attempts: 3

    depends_on:
      - income-route
      - middleman-route

    configs:
      - encoder_config

  vector_indexer:
    image: ${DOCKER_IMG_URL}
    command: >
      index --port_in ${MIDDLEMAN_ROUTE_OUT} --port_out ${OUTGOING_ROUTE_IN}
       --socket_in SUB_CONNECT --socket_out PUSH_CONNECT
       --host_in middleman-route --host_out outgoing-route
       --yaml_path /indexer_config --dump_path /out_data/index.bin
    volumes:
      - index_data:/out_data

    networks:
      gnes-net:
        aliases:
          - indexer_vector_serviced

    configs:
      - indexer_vector_config

  fulltext_indexer:
    image: ${DOCKER_IMG_URL}
    command: >
      index --port_in ${MIDDLEMAN_ROUTE_OUT} --port_out ${OUTGOING_ROUTE_IN}
       --socket_in SUB_CONNECT --socket_out PUSH_CONNECT
       --host_in middleman-route --host_out outgoing-route
       --yaml_path /indexer_config --dump_path /out_data/index.bin
    volumes:
      - index_data:/out_data

    networks:
      gnes-net:
        aliases:
          - indexer_fulltext_serviced

    configs:
      - indexer_fulltext_config

  frontend:
    image: ${DOCKER_IMG_URL}
    command: >
      frontend --port_in ${OUTGOING_ROUTE_OUT} --port_out ${PREPROCESSOR_IN}
       --host_in outgoing-route --host_out preprocess
       --socket_in SUB_CONNECT --socket_out PUSH_CONNECT
       --grpc_port ${GRPC_PORT}

    networks:
      gnes-net:
        aliases:
          - grpc_serviced

    depends_on:
      - preprocess
      - outgoing-route

    ports:
      - ${GRPC_PORT}:${GRPC_PORT}


volumes:
  index_data:
    name: "${GNES_STACK_NAME}_shard_{{ .Task.Slot }}_data"

networks:
  gnes-net:
    driver: overlay
    attachable: true

configs:
  encoder_config:
    file: "${ENCODER_YAML_PATH}"
  indexer_vector_config:
    file: "${INDEXER_VECTOR_YAML_PATH}"
  indexer_fulltext_config:
    file: "${INDEXER_FULLTEXT_YAML_PATH}"
  preprocessor_config:
    file: "${PREPROCESSOR_YAML_PATH}"