version: '3.4'
services:
  encoder:
    image: ${DOCKER_IMG_URL}
    networks:
      gnes-net:
        aliases:
          - encoder_serviced
    command: >
      encode --port_in ${INCOME_PROXY_IN} --port_out ${MIDDLEMAN_PROXY_IN}
        --socket_in PULL_BIND --socket_out PUSH_CONNECT
        --mode TRAIN --yaml_path /encoder_config --dump_path /dump/model.bin
    volumes:
      - "${MODEL_DIR}:/ext_data"
      - "${OUTPUT_DIR}:/dump"
    ports:
      - ${INCOME_PROXY_IN}:${INCOME_PROXY_IN}
    configs:
      - encoder_config

networks:
  gnes-net:

configs:
  encoder_config:
    file: "${ENCODER_YAML_PATH}"
