!PipelineEncoder
component:
  - !Word2VecEncoder
    parameter:
      model_dir: /ext_data/sgns.wiki.bigram-char.refine
    property:
      is_trained: true
  - !PCALocalEncoder
    parameter:
      output_dim: 200
      num_locals: 10
    property:
      batch_size: 2048
  - !PQEncoder
    parameter:
      cluster_per_byte: 20
      num_bytes: 10
  - !BinaryEncoder {}