version: '3.4'
services:
  income-proxy:
    image: ${DOCKER_IMG_URL}
    networks:
      larry-net:
        aliases:
          - income_porxy
    command: proxy --port_in ${INCOME_PROXY_IN} --port_out ${INCOME_PROXY_OUT} --socket_in PULL_BIND --socket_out PUSH_BIND --proxy_type=ProxyService
    ports:
      - ${INCOME_PROXY_IN}:${INCOME_PROXY_IN}
  encoder:
    image: ${DOCKER_IMG_URL}
    networks:
      gnes-net:
        aliases:
          - encoder_serviced2
    command: encode --port_in ${INCOME_PROXY_OUT} --port_out ${MIDDLEMAN_PROXY_IN}  --socket_in PULL_CONNECT --socket_out PUSH_CONNECT --mode $SERVER_MODE --yaml_path /test_encoder.yml --dump_path /dump/model.bin --host_in income-proxy --host_out middleman-proxy
    volumes:
      - "${YAML_PATH}/encoder.yml.${ENC_NAME}:/test_encoder.yml"
      - "${MODEL_DIR}:/ext_data"
      - "${ENC_DIR}/${ENC_NAME}:/dump"
    depends_on:
      - income-proxy
    deploy:
      placement:
        constraints: [node.role == worker]
networks:
  gnes-net: