!PipelineEncoder
component:
  - !BasePytorchEncoder
    parameter:
      model_dir: /ext_data/image_encoder
      model_name: vgg16
      layers:
        - features
        - avg_pool
        - x.view(x.size(0), -1)
        - classifier[0]
    property:
      is_trained: true
  - !PCALocalEncoder
    parameter:
      output_dim: 200
      num_locals: 10
    property:
      batch_size: 2048
  - !PQEncoder
    parameter:
      cluster_per_byte: 20
      num_bytes: 10
