!MultiheadIndexer
component:
  binary_indexer: !FaissIndexer
    parameter:
      num_dim: 300
      index_key: HNSW32
      data_path: /out_data/idx.faiss
  doc_indexer: !LVDBIndexer
    parameter:
      data_path: /out_data/idx.doc_content