!MultiheadIndexer
component:
  binary_indexer: !BIndexer
    parameter:
      num_bytes: 30
      data_path: /out_data/idx.binary
  doc_indexer: !LVDBIndexer
    parameter:
      data_path: /out_data/idx.doc_content
