version: '3.4'
services:
  preprocess:
    image: ${DOCKER_IMG_URL}
    command: >
      preprocess --port_in ${PREPROCESSOR_IN} --port_out ${INCOME_ROUTE_IN}
      --socket_in PULL_BIND --socket_out PUSH_CONNECT
      --host_out income-route
      --yaml_path /preprocessor_config --dump_path /dump/preprocessor.bin
    networks:
      gnes-net:
        aliases:
          - preprocessor_serviced
    configs:
      - preprocessor_config
    depends_on:
      - income-route

  income-route:
    image: ${DOCKER_IMG_URL}
    command: >
      route --router_type MapRouterService --port_in ${INCOME_ROUTE_IN} --port_out ${INCOME_ROUTE_OUT}
      --socket_in PULL_CONNECT --socket_out PUSH_BIND --batch_size=128
    networks:
      gnes-net:
        aliases:
          - income_route

  middleman-route:
    image: ${DOCKER_IMG_URL}
    command: >
      route --router_type=RouterService --port_in ${MIDDLEMAN_ROUTE_IN} --port_out ${MIDDLEMAN_ROUTE_OUT}
      --socket_in PULL_BIND --socket_out PUSH_BIND
    networks:
      gnes-net:
        aliases:
          - middleman_route

  outgoing-route:
    image: ${DOCKER_IMG_URL}
    command: >
      route --router_type=RouterService --port_in ${OUTGOING_ROUTE_IN} --port_out ${OUTGOING_ROUTE_OUT}
      --socket_in PULL_BIND --socket_out PUB_BIND
    networks:
      gnes-net:
        aliases:
          - outgoing_route

  encoder:
    image: ${DOCKER_IMG_URL}
    command: >
      encode --port_in ${INCOME_ROUTE_OUT} --port_out ${MIDDLEMAN_ROUTE_IN}
      --socket_in PULL_CONNECT --socket_out PUSH_CONNECT
      --host_in income-route --host_out middleman-route
      --yaml_path /encoder_config --dump_path /dump/model.bin
    volumes:
      - "${MODEL_DIR}:/ext_data"
      - "${OUTPUT_DIR}:/dump"
    networks:
      gnes-net:
        aliases:
          - encoder_serviced
    deploy:
      replicas: ${NUM_ENCODER}
      restart_policy:
        condition: on-failure
        max_attempts: 3

    depends_on:
      - income-route
      - middleman-route

    configs:
      - encoder_config

  indexer:
    image: ${DOCKER_IMG_URL}
    command: >
      index --port_in ${MIDDLEMAN_ROUTE_OUT} --port_out ${OUTGOING_ROUTE_IN}
       --socket_in PULL_CONNECT --socket_out PUSH_CONNECT
       --host_in middleman-route --host_out outgoing-route
       --yaml_path /indexer_config --dump_path /out_data/index.bin
    volumes:
      - index_data:/out_data
      #- type: volume
      #  source: "index_data"
      #  target: "/out_data"

      #- "${OUTPUT_DIR}/indexer_dump.{{.Task.Slot}}:/out_data"

    deploy:
      replicas: ${NUM_INDEXER}
      restart_policy:
        condition: on-failure
        max_attempts: 3

    environment:
      - NODE_ID={{.Node.ID}}
      - SERVICE_ID={{.Service.ID}}
      - SERVICE_NAME={{.Service.Name}}
      - SERVICE_LABELS={{.Service.Labels}}
      - TASK_ID={{.Task.ID}}
      - TASK_NAME={{.Task.Name}}
      - TASK_SLOT={{.Task.Slot}}

    networks:
      gnes-net:
        aliases:
          - index_serviced
    depends_on:
      - middleman-route
      - outgoing-route

    configs:
      - indexer_config

  frontend:
    image: ${DOCKER_IMG_URL}
    command: >
      frontend --port_in ${OUTGOING_ROUTE_OUT} --port_out ${PREPROCESSOR_IN}
       --host_in outgoing-route --host_out preprocess
       --socket_in SUB_CONNECT --socket_out PUSH_CONNECT
       --grpc_port ${GRPC_PORT}

    networks:
      gnes-net:
        aliases:
          - grpc_serviced

    depends_on:
      - preprocess
      - outgoing-route

    ports:
      - ${GRPC_PORT}:${GRPC_PORT}

  http_service:
    image: ${DOCKER_IMG_URL}
    command: >
       client_http --http_port=${HTTP_PORT} --grpc_port ${GRPC_PORT}  
        --grpc_host frontend  --max_workers=10
    networks:
      gnes-net:
        aliases:
          - http_serviced
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - encoder
      - indexer
      - outgoing-proxy
      - income-proxy

volumes:
  index_data:
    name: "${GNES_STACK_NAME}_shard_{{ .Task.Slot }}_data"

networks:
  gnes-net:
    driver: overlay
    attachable: true

configs:
  encoder_config:
    file: "${ENCODER_YAML_PATH}"
  indexer_config:
    file: "${INDEXER_YAML_PATH}"
  preprocessor_config:
    file: "${PREPROCESSOR_YAML_PATH}"