version: '3.4'
services:
  preprocess:
    image: ${DOCKER_IMG_URL}
    command: >
      preprocess --port_in ${PREPROCESSOR_IN} --port_out ${INCOME_ROUTE_IN}
       --socket_in PULL_BIND --socket_out PUSH_CONNECT
       --host_out encoder_serviced
       --yaml_path /preprocessor_config --dump_path /dump/preprocessor.bin
    networks:
      gnes-net:
        aliases:
          - preprocessor_serviced
    configs:
      - preprocessor_config

  encoder:
    image: ${DOCKER_IMG_URL}
    networks:
      gnes-net:
        aliases:
          - encoder_serviced
    command: >
      encode --port_in ${INCOME_ROUTE_IN} --port_out ${OUTGOING_ROUTE_OUT}
        --socket_in PULL_BIND --socket_out PUB_BIND
        --yaml_path /encoder_config --dump_path /dump/model.bin
    volumes:
      - "${MODEL_DIR}:/ext_data"
      - "${OUTPUT_DIR}:/dump"
    configs:
      - encoder_config

  frontend:
    image: ${DOCKER_IMG_URL}
    command: >
      frontend --port_in ${OUTGOING_ROUTE_OUT} --port_out ${PREPROCESSOR_IN}
       --host_in encoder_serviced --host_out preprocessor_serviced
       --socket_in SUB_CONNECT --socket_out PUSH_CONNECT
       --grpc_port ${GRPC_PORT}

    networks:
      gnes-net:
        aliases:
          - grpc_serviced

    ports:
      - ${GRPC_PORT}:${GRPC_PORT}


  http_service:
    image: ${DOCKER_IMG_URL}
    command: >
       client_http --http_port=${HTTP_PORT} --grpc_port ${GRPC_PORT}  
        --grpc_host frontend  --max_workers=10
    networks:
      gnes-net:
        aliases:
          - http_serviced
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - encoder
      - indexer
      - outgoing-proxy
      - income-proxy

networks:
  gnes-net:
    driver: overlay
    attachable: true

configs:
  encoder_config:
    file: "${ENCODER_YAML_PATH}"
  preprocessor_config:
    file: "${PREPROCESSOR_YAML_PATH}"
