version: '3.4'
services:
  encoder:
    image: ${DOCKER_IMG_URL}
    networks:
      larry-net:
        aliases:
          - encoder_serviced
    command: encode --port_in ${INCOME_PROXY_IN} --port_out ${MIDDLEMAN_PROXY_IN}  --socket_in PULL_BIND --socket_out PUSH_CONNECT --mode TRAIN --yaml_path /test_encoder.yml --dump_path /dump/model.bin
    volumes:
      - "${YAML_PATH}/encoder.yml.${ENC_NAME}:/test_encoder.yml"
      - "${MODEL_DIR}:/ext_data"
      - "${ENC_DIR}/${ENC_NAME}:/dump"
    ports:
      - ${INCOME_PROXY_IN}:${INCOME_PROXY_IN}
networks:
  larry-net:
